name: 'simple-npm-publish-and-tag-action'
description: 'A simple action for publishing to npm and creating a Git tag (if publish is successful).'
author: 'Alex MacArthur'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  npm_token:
    description: 'The NPM_TOKEN required for publishing to npm.'
    required: true
runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/
    - uses: fregante/setup-git-user@v1
    - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      env:
        NPM_TOKEN: ${{inputs.npm_token}}
    - run: npm install
    - run: npm run build
    - run: |
        if npm publish --access public; then
          PACKAGE_VERSION=$(grep version package.json | cut -c 15- | rev | cut -c 3- | rev)
          git tag -a v$PACKAGE_VERSION -m "Create release v$PACKAGE_VERSION."
          git push --tags
        fi
